### ISSUE TITLE
Upload and insert error

### ISSUE THREAD

**Issue by Tazzios** [JoomGalleryfriends/JoomMediaFormField#1]
issue:
1. use the mediaform to add an intro image
2. choose for image upload
3. select image and click on insert

Expected:
New uploaded image added as intro image

result:
Opens the site in the popupbox and intro image not added

enviroment
Joomgalley: 3.3.5
Joomla 3.9.11
PHP 7.2

**Comment by MrMusic** [comment]
Hi,
thank you for your hint.
Please use the following workflow:

1. Use the mediaform to add an intro image
2. Choose tab 'Upload image' and upload the new image
3. Choose tab 'Insert image' and select the new image to use as intro image

**Comment by Tazzios** [comment]
I assume you mean that as workaround?
The interface shows clearly that is should be possible directly. And with the button in the content editor it does work.
See this image, i have uploaded an image and when the upload is finished there is an direct option to add one image.
![joomimage upload](https://user-images.githubusercontent.com/23451105/68469481-87dc7a00-021a-11ea-94dc-90650af8073f.png)

**Comment by Erftralle** [comment]
> I assume you mean that as workaround?

Yes, better to have a workaround than nothing 😉 .

To fix that problem it is necessary to add code to the JoomGallery itself, not to the plugin code. Please have a look at JoomGalleryfriends/JoomGallery#23. Please test and give feedback. Thank you.

**Comment by Tazzios** [comment]
Tried the plugin:
- On my test site the image upload is now totally broken.
- reinstalling the 3.3.5 did not help.

So to be sure i made a fresh joomla installation.
- There it works.
- But the normal version without the fix also works. 

The testing i did in the backend to prevent template errors.
So i turned on debug mode to get some more info, but there is nothing to see.

Possible options:
1. Conflict with other editor buttons/ content plugins.
2. Left overs of older version of joomgallery or joomla files.
3. ?

 If i can provide you with other information or testing let me know. I can also give you access to my test installation if you like.

**Comment by MrMusic** [comment]
>To fix that problem it is necessary to add code to the JoomGallery itself, not to the plugin code. Please have a look at JoomGalleryfriends/JoomGallery#23. Please test and give feedback. Thank you.

I have tested this fix successfully with Joomla 3.9.13.

@Tazzios: Do you delete all caches (Joomla and Browser)?

**Comment by Erftralle** [comment]
@Tazzios:
Thanks for the tests, but, do not take it personally, I doubt your test results.

You tell us, that in your tests, the bug that you reported above is not reproducible in a fresh install, neither with nor without the changes of JoomGalleryfriends/JoomGallery#23. 
So that means we could simply close this issue?

I can (and I think @MrMusic also) reproduce the bug reported above perfectly. There is definitely no code in JoomGallery for the 'Insert' functionality, it can not work without changes. So unfortunately I have to doubt your results.

**Comment by Tazzios** [comment]
You guys are right to doubt my (monday) test skills, I was adding an image in the article instead of intro or full image.
Installed the fix on 3 websites and it works on all of them. :)

Thanks for the quickfix!

**Comment by Erftralle** [comment]
Thanks at all for testing and giving feedback!
